FROM python:3.9-slim

# Below was results of pip freeze after running
#RUN pip install pandas  \
#    sqlalchemy  \
#    mysql-connector-python  \
#    openai  \
#    langchain \
#    beautifulsoup4  \
#    lxml

RUN pip install aiohttp==3.8.5 \
                 aiosignal==1.3.1 \
                 async-timeout==4.0.3 \
                 attrs==23.1.0 \
                 beautifulsoup4==4.12.2 \
                 certifi==2023.7.22 \
                 charset-normalizer==3.2.0 \
                 dataclasses-json==0.5.14 \
                 frozenlist==1.4.0 \
                 greenlet==2.0.2 \
                 idna==3.4 \
                 langchain==0.0.265 \
                 langsmith==0.0.22 \
                 lxml==4.9.3 \
                 marshmallow==3.20.1 \
                 multidict==6.0.4 \
                 mypy-extensions==1.0.0 \
                 mysql-connector-python==8.1.0 \
                 numexpr==2.8.5 \
                 numpy==1.25.2 \
                 openai==0.27.8 \
                 openapi-schema-pydantic==1.2.4 \
                 packaging==23.1 \
                 pandas==2.0.3 \
                 protobuf==4.21.12 \
                 pydantic==1.10.12 \
                 python-dateutil==2.8.2 \
                 pytz==2023.3 \
                 PyYAML==6.0.1 \
                 requests==2.31.0 \
                 six==1.16.0 \
                 soupsieve==2.4.1 \
                 SQLAlchemy==2.0.20 \
                 tenacity==8.2.3 \
                 tqdm==4.66.1 \
                 typing-inspect==0.9.0 \
                 typing_extensions==4.7.1 \
                 tzdata==2023.3 \
                 urllib3==2.0.4 \
                 yarl==1.9.2